import React from 'react';
import { Alert, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { Colors } from '../constants/colors';
import { TvControlService } from '../services/TvControlService';
import { useDeviceStore } from '../store/deviceStore';

type Props=NativeStackScreenProps<{DeviceDetails:{deviceId:string}},'DeviceDetails'>;
const DeviceDetailsScreen:React.FC<Props>=({route})=>{
  const {deviceId}=route.params; const {devices,updateDevice,removeDevice}=useDeviceStore(); const device=devices.find(item=>item.deviceId===deviceId);
  const run=async(label:string,action:()=>Promise<unknown>)=>{try{await action();Alert.alert(label,'Command sent.');}catch(error:any){Alert.alert(`${label} failed`,error?.message||'Command could not be completed. The TV has not been removed; try Refresh TV Info.');}};
  const refresh=async()=>{try{const info=await TvControlService.getDeviceInfo(deviceId);updateDevice(deviceId,{state:'Connected',deviceInfo:{serial:info['ro.serialno']||'',manufacturer:info['ro.product.manufacturer']||'',model:info['ro.product.model']||'',androidVersion:info['ro.build.version.release']||'',sdkVersion:Number(info['ro.build.version.sdk'])||0,screenResolution:info.screen_size||'',density:info.density||'',storage:info.storage||''}});}catch(error:any){Alert.alert('Refresh failed',error?.message||'TV information could not be read.');}};
  if(!device)return <View style={s.container}><Text style={s.text}>TV not found.</Text></View>;
  const info=device.deviceInfo; const rotate=(value:number)=>run('Display rotation',()=>TvControlService.shell(deviceId,`settings put system accelerometer_rotation 0; settings put system user_rotation ${value}`));
  return <ScrollView style={s.container} contentContainerStyle={s.content}><View style={s.header}><Text style={s.title}>{device.name}</Text><Text style={s.text}>{device.ipAddress}:{device.port} · {device.state}</Text></View>{[['Model',info?.model],['Manufacturer',info?.manufacturer],['Android',info?.androidVersion],['SDK',String(info?.sdkVersion||'')],['Resolution',info?.screenResolution],['Density',info?.density],['Storage',info?.storage]].map(([key,value])=><View key={key} style={s.info}><Text style={s.label}>{key}</Text><Text style={s.text}>{value||'Unknown'}</Text></View>)}<TouchableOpacity style={s.button} onPress={refresh}><Text style={s.bt}>REFRESH TV INFO</Text></TouchableOpacity><Text style={s.heading}>Display rotation</Text><View style={s.grid}>{[['LANDSCAPE',0],['PORTRAIT',1],['REVERSE LANDSCAPE',2],['REVERSE PORTRAIT',3]].map(([name,value])=><TouchableOpacity key={String(name)} style={s.small} onPress={()=>rotate(Number(value))}><Text style={s.bt}>{String(name)}</Text></TouchableOpacity>)}</View><Text style={s.heading}>Power & connection</Text><View style={s.grid}>{[['WAKE',()=>TvControlService.screenOn(deviceId)],['SLEEP',()=>TvControlService.screenOff(deviceId)],['REBOOT',()=>TvControlService.rebootDevice(deviceId)],['DISCONNECT',async()=>{await TvControlService.disconnectDevice(deviceId);removeDevice(deviceId);}]].map(([name,action])=><TouchableOpacity key={String(name)} style={[s.small,name==='DISCONNECT'&&s.danger]} onPress={()=>run(String(name),action as ()=>Promise<unknown>)}><Text style={s.bt}>{String(name)}</Text></TouchableOpacity>)}</View></ScrollView>;
};
const s=StyleSheet.create({container:{flex:1,backgroundColor:Colors.background},content:{paddingBottom:110},header:{padding:20,borderBottomWidth:1,borderBottomColor:Colors.border},title:{fontSize:24,fontWeight:'bold',color:Colors.text},info:{marginHorizontal:16,marginTop:10,backgroundColor:Colors.surface,padding:14,borderRadius:8},label:{fontSize:12,color:Colors.textSecondary},text:{fontSize:15,color:Colors.text,marginTop:4},button:{margin:16,backgroundColor:Colors.primary,padding:14,borderRadius:8,alignItems:'center'},bt:{color:Colors.text,fontSize:12,fontWeight:'bold',textAlign:'center'},heading:{color:Colors.text,fontSize:17,fontWeight:'bold',padding:16},grid:{flexDirection:'row',flexWrap:'wrap',paddingHorizontal:12,gap:8},small:{width:'47%',backgroundColor:Colors.surfaceLight,padding:13,borderRadius:8,alignItems:'center'},danger:{backgroundColor:Colors.error}});
export default DeviceDetailsScreen;
