import React from 'react';
import { Alert, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Colors } from '../constants/colors';
import { TvControlService } from '../services/TvControlService';
import { getSelectedConnectedDevices } from '../utils/selectedDevice';
import { KeyCodes } from '../constants/keycodes';
const MenuScreen:React.FC=()=>{const [busy,setBusy]=React.useState(false);const run=async(label:string,task:(id:string)=>Promise<unknown>)=>{try{const devices=getSelectedConnectedDevices();setBusy(true);const r=await Promise.allSettled(devices.map(d=>task(d.deviceId)));Alert.alert(label,`Applied to ${r.filter(x=>x.status==='fulfilled').length}/${devices.length} selected TV(s).`);}catch(e:any){Alert.alert(`${label} failed`,e?.message||'Select a connected TV first.');}finally{setBusy(false);}};const info=async(label:string,cmd:string)=>{try{const d=getSelectedConnectedDevices()[0];setBusy(true);const r=await TvControlService.shell(d.deviceId,cmd);Alert.alert(`${label} · ${d.name}`,(r.stdout||'No data returned.').trim().split(/\r?\n/).filter(Boolean).slice(0,8).join('\n'));}catch(e:any){Alert.alert(`${label} failed`,e?.message||'Unable to read information.');}finally{setBusy(false);}};const keys=(codes:number[])=>run('TV service menu',async id=>{for(const c of codes)await TvControlService.sendKeyEvent(id,c);});return <ScrollView style={s.container} contentContainerStyle={s.content}><View style={s.header}><Text style={s.title}>System Menu</Text><Text style={s.hint}>Short, structured information from the first selected TV. Service actions apply to all selected TVs.</Text></View><Text style={s.heading}>System information</Text><View style={s.grid}><Action label="CHECK IP ADDRESS" busy={busy} onPress={()=>info('IP address','ip route get 1.1.1.1')}/><Action label="CHECK WI-FI STATUS" busy={busy} onPress={()=>info('Wi-Fi status','dumpsys wifi | grep -E "SSID|Wi-Fi is|mNetworkInfo"')}/><Action label="CHECK CONNECTIVITY" busy={busy} onPress={()=>info('Connectivity','getprop | grep -E "net\\.|wifi\\."')}/><Action label="OPEN DEVELOPER OPTIONS" busy={busy} onPress={()=>run('Developer options',id=>TvControlService.shell(id,'am start -a android.settings.APPLICATION_DEVELOPMENT_SETTINGS'))}/></View><Text style={s.heading}>TV service menus</Text><View style={s.grid}><Action label="GOOGLE TV: INPUT → L L U D" busy={busy} onPress={()=>keys([KeyCodes.INPUT,21,21,19,20])}/><Action label="CUSTOM TV: HOME → INPUT → L R L R → BACK" busy={busy} onPress={()=>keys([3,KeyCodes.INPUT,21,22,21,22,4])}/><Action label="SMART TV: MENU → 1 → 1 → 4 → 7" busy={busy} onPress={()=>keys([KeyCodes.MENU,8,8,11,14])}/><Action label="SMART TV (208)" busy={busy} onPress={()=>run('Smart TV 208',id=>TvControlService.sendKeyEvent(id,208))}/></View></ScrollView>;};
const Action=({label,busy,onPress}:{label:string;busy:boolean;onPress:()=>void})=><TouchableOpacity style={[s.button,busy&&s.disabled]} disabled={busy} onPress={onPress}><Text style={s.buttonText}>{label}</Text></TouchableOpacity>;
const s=StyleSheet.create({container:{flex:1,backgroundColor:Colors.background},content:{paddingBottom:40},header:{padding:20,borderBottomWidth:1,borderBottomColor:Colors.border},title:{fontSize:24,fontWeight:'bold',color:Colors.text},hint:{fontSize:13,color:Colors.textSecondary,marginTop:5},heading:{fontSize:17,fontWeight:'bold',color:Colors.text,paddingHorizontal:16,paddingTop:22,paddingBottom:10},grid:{paddingHorizontal:16,gap:10},button:{backgroundColor:Colors.surface,padding:15,borderRadius:10,borderWidth:1,borderColor:Colors.border},buttonText:{fontSize:14,fontWeight:'600',color:Colors.text},disabled:{opacity:.55}});export default MenuScreen;
