import React from 'react';
import { ActivityIndicator, Alert, Platform, StatusBar, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Colors } from '../constants/colors';
import { TvControlService } from '../services/TvControlService';
import { useDeviceStore } from '../store/deviceStore';

export const GlobalHeader=({navigation}:{navigation:any})=>{
  const {devices,addDevice}=useDeviceStore(); const [busy,setBusy]=React.useState<'refresh'|'scan'|null>(null);
  const online=devices.filter(d=>d.state==='Connected').length; const offline=devices.length-online;
  const refresh=async()=>{setBusy('refresh');try{const list=await TvControlService.getConnectedDevices();list.forEach((device:any)=>addDevice({...device,state:'Connected'}));Alert.alert('Controller refreshed',`${list.length} TV connection(s) active.`);}catch(error:any){Alert.alert('Refresh failed',error?.message||'Unable to refresh controller.');}finally{setBusy(null);}};
  const scan=async()=>{setBusy('scan');try{const endpoints=await TvControlService.scanWifiDevices();const results=await Promise.allSettled(endpoints.map((item:any)=>TvControlService.connectWifiDevice(item.ipAddress,item.port)));results.forEach(result=>{if(result.status==='fulfilled')addDevice(result.value);});Alert.alert('Scan complete',`${results.filter(r=>r.status==='fulfilled').length}/${endpoints.length} TV(s) connected.`);navigation.navigate('TVs');}catch(error:any){Alert.alert('Scan failed',error?.message||'Ensure the controller and TV are on the same Wi-Fi.');}finally{setBusy(null);}};
  return <View style={s.header}><View style={s.top}><Text style={s.brand}>TV Control Center</Text><View style={s.actions}><TouchableOpacity style={s.action} onPress={refresh} disabled={!!busy}>{busy==='refresh'?<ActivityIndicator color={Colors.text}/>:<Text style={s.actionText}>REFRESH</Text>}</TouchableOpacity><TouchableOpacity style={[s.action,s.scan]} onPress={scan} disabled={!!busy}>{busy==='scan'?<ActivityIndicator color={Colors.text}/>:<Text style={s.actionText}>SCAN</Text>}</TouchableOpacity></View></View><View style={s.stats}><TouchableOpacity onPress={()=>navigation.navigate('TVs')}><Text style={s.stat}>CONNECTED <Text style={s.value}>{online}</Text></Text></TouchableOpacity><TouchableOpacity onPress={()=>navigation.navigate('TVs')}><Text style={s.online}>ONLINE <Text style={s.value}>{online}</Text></Text></TouchableOpacity><TouchableOpacity onPress={()=>navigation.navigate('TVs')}><Text style={s.offline}>OFFLINE <Text style={s.value}>{offline}</Text></Text></TouchableOpacity></View></View>;
};
const s=StyleSheet.create({header:{backgroundColor:Colors.surface,borderBottomWidth:1,borderBottomColor:Colors.border,paddingHorizontal:14,paddingTop:(Platform.OS==='android'?(StatusBar.currentHeight||24):24)+10,paddingBottom:8},top:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},brand:{color:Colors.text,fontWeight:'bold',fontSize:17},actions:{flexDirection:'row',gap:7},action:{backgroundColor:Colors.surfaceLight,paddingVertical:8,paddingHorizontal:10,borderRadius:7,minWidth:65,alignItems:'center'},scan:{backgroundColor:Colors.primary},actionText:{color:Colors.text,fontWeight:'700',fontSize:11},stats:{marginTop:10,flexDirection:'row',justifyContent:'space-between'},stat:{color:Colors.textSecondary,fontSize:11},online:{color:Colors.success,fontSize:11},offline:{color:Colors.error,fontSize:11},value:{color:Colors.text,fontWeight:'bold'}});
